version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    ignore:
      # Ignore 5.0 major release of history package
      - dependency-name: "history"
        versions: ["5.x"]
      # Ignore 6.0 react router upgrade until https://reactrouter.com/docs/en/v6/upgrading/v5#prompt-is-not-currently-supported is resolved
      - dependency-name: "react-router-dom"
        versions: [ "6.x" ]
    open-pull-requests-limit: 1
